# Generated by Django 3.1.2 on 2020-11-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='auto',
            new_name='vehiculo',
        ),
    ]
