# Generated by Django 3.1.2 on 2020-11-10 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20201105_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['proveedor']},
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehicle.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_vehiculo', to='vehicle.categoria'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_de_combustible', to='vehicle.combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_vehiculo', to='vehicle.estado'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_proveedor', to='vehicle.proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('proveedor',)},
        ),
    ]
