# Generated by Django 3.1.2 on 2020-11-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20201109_2136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together=set(),
        ),
    ]
