# Generated by Django 3.1.2 on 2020-11-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20201109_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_puja', models.FloatField()),
                ('fecha_puja', models.DateTimeField()),
                ('cliente', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.categoria'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.estado'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.proveedor'),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_vehiculo', models.FloatField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('cliente', models.IntegerField()),
                ('puja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_puja', to='vehicle.puja')),
                ('vehiculo_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_veh', to='vehicle.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='puja',
            name='vehiculo_puja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aumento_precio', to='vehicle.vehiculo'),
        ),
    ]
