# Generated by Django 3.1.2 on 2020-11-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20201110_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='modelo',
        ),
    ]
